### ISSUE TITLE
Что за датасеты?

### ISSUE THREAD

**Issue by xan4ik** [fizmat/hopfield-tracking#12]
В файле optimize.py нет сообщения о том, из каких датасетов выбирать или где их искать
![image](https://user-images.githubusercontent.com/40671586/191783599-fab277cc-5ced-4059-8e9e-d5fa3f5503e0.png)

**Comment by fizmat** [comment]
Вы правы, надо сообщить argparse возможные значения этого аргумента, тогда он их подскажет при вызове.

**Comment by ann1221** [comment]
Я возьму
