### ISSUE TITLE
Отсутствие файла (stat_seg_neighbors требует bman датасет)

### ISSUE THREAD

**Issue by AlxDidorenko** [fizmat/hopfield-tracking#14]
Из-за отсутствия файла simdata_ArPb_3.2AGeV_mb_1.zip в stat_seg_neighbors.ipynb, не запускается код
![image](https://user-images.githubusercontent.com/47829900/191784172-ee07fd64-d294-4562-9ae3-ec89602f98c0.png)

**Comment by fizmat** [comment]
stat_seg_neighbors требует полный bman датасет, надо это упомянуть в блокноте и наверное в readme.

**Comment by Borpa** [comment]
Взял в работу
