### ISSUE TITLE
profile_seg_pools.ipynb : использование комманды head вызывает ошибку на windows 8 

### ISSUE THREAD

**Issue by Borpa** [fizmat/hopfield-tracking#17]
![изображение](https://user-images.githubusercontent.com/114162087/191786562-86b8cae9-19e7-47ff-8cf2-851eccc6fc58.png)

**Comment by fizmat** [comment]
Вариант 1 (по-моему плохой) - найти альтернативу head в windows. Понятно почему плохой - разный код в разных ситуациях, что неудобно. Да и смысл кода ведь не в head, а в том чтобы показать текущий коммит.
Вариант 2 (хороший) - вспомнить как в git показать только последний коммит.

**Comment by AlxDidorenko** [comment]
Решение!
!git log -1
