### ISSUE TITLE
Проблема потребления большого количества памяти

### ISSUE THREAD

**Issue by Morsala** [fizmat/hopfield-tracking#20]
На ноутбуках, у которых памяти в общем остается около 20 Гб, создание окружения является очень затратным в плане используемой памяти. Почти все дисковое пространство заполняется.

**Comment by fizmat** [comment]
Во-первых все-таки дискового пространства. Паматью его лучше не называть, иначе будет путаница с оперативной памятью, которой в ноутбуках обычно сильно меньше 20 Гб.
Проблема повторяет #3 и #13, но действительно надо решать.
