### ISSUE TITLE
Недостаточность данных в главе Experiment внутри README файла

### ISSUE THREAD

**Issue by ann1221** [fizmat/hopfield-tracking#25]
При старте работы с проектом не удается следовать инструкциям внутри главы Experiment, так как указанного в инструкциях файла main.ipynb нет внутри проекта
![image](https://user-images.githubusercontent.com/55325679/204906072-4e01c28b-77f1-465b-9dbb-357c0d5c8f36.png)
![image](https://user-images.githubusercontent.com/55325679/204907484-b4208445-47af-4506-ae7f-83991ca27fe0.png)

**Comment by fizmat** [comment]
- дубликат #6
- уже исправлено

Лучше искать ошибки и работать с веткой dev, там уже много хороших исправлений по сравнению с мастером.
