### ISSUE TITLE
README репозитория устарел (новые jupyter блокноты)

### ISSUE THREAD

**Issue by AlxDidorenko** [fizmat/hopfield-tracking#6]
Хозяин репозитория не следит за актуальностью README-файла репозитоирия. Отображается старая информация. 
Так, указано, что можно выполнить jupiter lab main.ipynb, но в самом репозитории нет этого файла.

**Comment by fizmat** [comment]
Надо добавить в readme все блокноты и запускаемые файлы с пояснениями.

**Comment by fizmat** [comment]
Исправлено в e59b919abc19662c08736e165a0094394c140d7d
